import { Lead } from './lead.model';

/**
 * Authored demonstration content — not real customers.
 * Stands in for the Supabase `leads` table until the schema is deployed; the shapes
 * match docs/ARCHITECTURE.md §5 exactly, so swapping in supabase-js is a data-source
 * change, not a model change.
 */

const DAY = 86_400_000;
const ago = (days: number, hour = 10): Date => {
  const d = new Date(Date.now() - days * DAY);
  d.setHours(hour, 0, 0, 0);
  return d;
};

let seq = 0;
const id = () => `demo-${(++seq).toString().padStart(2, '0')}`;

export const DEMO_LEADS: Lead[] = [
  {
    id: id(),
    name: 'מיכל ברנר',
    company: 'ברנר ושות׳',
    email: 'michal@brenner.co.il',
    phone: '052-4410982',
    source: 'referral',
    status: 'proposal_sent',
    estimatedValue: 18000,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(24),
    lastTouchAt: ago(5),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 5,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'סטודיו פרג׳',
    company: 'מיכל פרג׳',
    email: 'hello@farge.studio',
    phone: '054-7728310',
    source: 'website',
    status: 'qualified',
    estimatedValue: 7400,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(11),
    lastTouchAt: ago(1),
    reminderDueAt: ago(0),
    reminderTitle: 'לחזור אחרי הפגישה',
    checklistAnswered: 3,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'דניאל חדד',
    company: 'חדד תקשורת',
    email: 'daniel@hadad.co.il',
    phone: '050-3319074',
    source: 'social_media',
    status: 'new',
    estimatedValue: 3200,
    lostReason: null,
    isDemo: false,
    assignedTo: 'דנה אבידן',
    createdAt: ago(1),
    lastTouchAt: null,
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 0,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'רן אלגריסי',
    company: 'אלגריסי ובניו',
    email: 'ran@algrisi.co.il',
    phone: '053-8820145',
    source: 'referral',
    status: 'won',
    estimatedValue: 9800,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(42),
    lastTouchAt: ago(0),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 5,
    clearedToday: 'נסגר בהצלחה',
  },
  {
    id: id(),
    name: 'אורית לוי',
    company: 'לוי הפקות',
    email: 'orit@levi-productions.co.il',
    phone: '052-6640238',
    source: 'referral',
    status: 'qualified',
    estimatedValue: 12500,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(45),
    lastTouchAt: ago(9),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 4,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'כרמל דיגיטל',
    company: 'נטע כרמל',
    email: 'neta@carmel.digital',
    phone: '054-2201877',
    source: 'website',
    status: 'proposal_sent',
    estimatedValue: 45000,
    lostReason: null,
    isDemo: false,
    assignedTo: 'דנה אבידן',
    createdAt: ago(30),
    lastTouchAt: ago(2),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 5,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'נועה שגב',
    company: null,
    email: 'noa.segev@gmail.com',
    phone: '050-9917426',
    source: 'phone',
    status: 'contacted',
    estimatedValue: 2100,
    lostReason: null,
    isDemo: false,
    assignedTo: 'דנה אבידן',
    createdAt: ago(35),
    lastTouchAt: ago(4),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 2,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'אבי מזרחי',
    company: 'מזרחי מיזוג אוויר',
    email: 'avi@mizrahi-ac.co.il',
    phone: '052-3308811',
    source: 'social_media',
    status: 'new',
    estimatedValue: 6300,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(0),
    lastTouchAt: ago(0),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 1,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'שירה בן־דוד',
    company: 'בן־דוד עיצוב פנים',
    email: 'shira@bendavid.design',
    phone: '053-4471290',
    source: 'website',
    status: 'contacted',
    estimatedValue: 22000,
    lostReason: null,
    isDemo: false,
    assignedTo: 'דנה אבידן',
    createdAt: ago(28),
    lastTouchAt: ago(6),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 2,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'טל אבידן',
    company: 'אבידן ייעוץ',
    email: 'tal@avidan.co.il',
    phone: '054-6612093',
    source: 'referral',
    status: 'won',
    estimatedValue: 15600,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(60),
    lastTouchAt: ago(24),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 5,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'בית קפה לבנון',
    company: 'יוסי לבנון',
    email: 'yossi@levanon.cafe',
    phone: '050-2214408',
    source: 'phone',
    status: 'lost',
    estimatedValue: 1800,
    lostReason: 'מחיר',
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(61),
    lastTouchAt: ago(21),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 5,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'גלית אשכנזי',
    company: 'אשכנזי נדל״ן',
    email: 'galit@ashkenazi-re.co.il',
    phone: '052-7730164',
    source: 'website',
    status: 'contacted',
    estimatedValue: 31000,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(19),
    lastTouchAt: ago(3),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 3,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'מוסך אחים דוד',
    company: 'איציק דוד',
    email: 'itzik@davidgarage.co.il',
    phone: '053-9902471',
    source: 'other',
    status: 'new',
    estimatedValue: 4200,
    lostReason: null,
    isDemo: false,
    assignedTo: 'דנה אבידן',
    createdAt: ago(4),
    lastTouchAt: null,
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 0,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'יעל רוזנברג',
    company: 'רוזנברג ייעוץ מס',
    email: 'yael@rosenberg-tax.co.il',
    phone: '054-1128806',
    source: 'referral',
    status: 'won',
    estimatedValue: 8900,
    lostReason: null,
    isDemo: false,
    assignedTo: 'רמי שגב',
    createdAt: ago(70),
    lastTouchAt: ago(30),
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 5,
    clearedToday: null,
  },
  {
    id: id(),
    name: 'מסעדת הגן',
    company: 'ליד לדוגמה',
    email: null,
    phone: '03-0000000',
    source: 'other',
    status: 'new',
    estimatedValue: 5000,
    lostReason: null,
    isDemo: true,
    assignedTo: null,
    createdAt: ago(0),
    lastTouchAt: null,
    reminderDueAt: null,
    reminderTitle: null,
    checklistAnswered: 0,
    clearedToday: null,
  },
];
